<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <form>
                <?= $this->form->field('q'); ?>
                <div class="form-group text-right">
                    <button class="btn btn-default">Find</button>
                </diV>
            </form>
            <div class="panel panel-default">
                <div class="panel-body">
                    Total result: <?= number_format($total, 0, '.','.'); ?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="page-header">
                <?php if($this->can_i->create_post_tag): ?>
                <a class="btn btn-primary pull-right" href="<?= $this->router->to('adminPostTagEdit', ['id'=>0], ['ref'=>$reff]) ?>">Create New</a>
                <?php endif; ?>
                <h3>Post Tags</h3>
            </div>
            
            <?php if($tags): ?>
            <?php
                $can_delete     = $this->can_i->remove_post_tag;
                $can_edit       = $this->can_i->update_post_tag;
            ?>
            
            <div class="list-group">
                <?php foreach($tags as $tag): ?>
                <div class="list-group-item">
                    
                    <div class="btn-group btn-group-xs pull-right" role="group">
                        
                        <?php if($can_edit): ?>
                        <a href="<?= $this->router->to('adminPostTagEdit', ['id'=>$tag->id], ['ref'=>$reff]) ?>" class="btn btn-default" title="Edit">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <?php endif; ?>
                        
                        <button id="tag-<?= $tag->id ?>" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-default btn-xs">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="tag-<?= $tag->id ?>">
                            <li>
                                <a href="<?= $tag->page ?>">
                                    <i class="fa fa-external-link" aria-hidden="true"></i> View page
                                </a>
                            </li>
                        <?php if($can_delete): ?>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="<?= $this->router->to('adminPostTagRemove', ['id'=>$tag->id], ['ref'=>$reff]) ?>" data-confirm="Delete Confirmation" data-confirm-message="Are you sure want to delete this post tag? This action can't be undone." title="Delete" aria-label="Delete">
                                    <i class="fa fa-trash" aria-hidden="true"></i> Delete
                                </a>
                            </li>
                        <?php endif; ?>
                        </ul>
                        
                    </div>
                    
                    <h4 class="list-group-item-heading">
                        <?= $tag->name ?>
                        <small><?= $tag->slug ?></small>
                    </h4>
                    <p class="list-group-item-text small">
                        <span title="Created"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i> <?= date('M d, Y', strtotime($tag->created)) ?></span>
                    </p>
                </div>
                <?php endforeach; ?>
            </div>
            
            <?php
                if($pagination)
                    $this->partial('shared/pagination', ['pagination'=>$pagination]);
            ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>